// firebase_options.dart
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static const FirebaseOptions currentPlatform = android;

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAwb5gBkwQ4U7po-hFHvdJ9t7c3Y79dWU',
    appId: '1:795827557508:android:dd55d514d2de653a37ded1',
    messagingSenderId: '795827557508',
    projectId: 'todolist-ef212',
    storageBucket: 'todolist-ef212.appspot.com',
  );
}
